# This is a basic workflow to help you get started with Actions

name: Automerge to feature/migrate-to-vc30

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev-3.0.0 ]
  pull_request:
    branches: none

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2  

      # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        gh_actor_profile="$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" "https://api.github.com/users/${GITHUB_ACTOR}")"
        git config --global user.name "$(printf '%s' "$gh_actor_profile" | jq -r .name)"
        git config --global user.email "$(printf '%s' "$gh_actor_profile" | jq -r .email)"

        git fetch
        git checkout feature/migrate-to-vc30
        git pull
        git merge dev-3.0.0